import { createContext, useCallback, useContext, useMemo } from 'react';
import type { ReactNode } from 'react';
import type { AppNotification, NotificationType } from '../types';
import { useAuth } from './useAuth';
import { useCollection } from '../lib/useCollection';
import { notificationFromRow } from '../lib/mappers';
import type { NotificationRow } from '../lib/database.types';

export interface NotificationPushInput {
  title: string;
  body: string;
  type?: NotificationType;
  link?: string;
}

interface NotificationsContextValue {
  notifications: AppNotification[];
  unreadCount: number;
  push: (input: NotificationPushInput) => void;
  markRead: (id: string) => void;
  markAllRead: () => void;
  clearAll: () => void;
}

const NotificationsContext = createContext<NotificationsContextValue | null>(null);

/**
 * Reminders now live in the database, so they reach the person on whichever
 * device they are using instead of being trapped in one browser's
 * localStorage. The id is generated by the database, so push() stays
 * fire-and-forget and the list stays consistent.
 */
export function NotificationsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();

  const collection = useCollection<NotificationRow, AppNotification>({
    table: 'notifications',
    map: notificationFromRow,
    order: { column: 'created_at', ascending: false },
    enabled: Boolean(user),
  });

  // Keep only the 40 most recent, matching the old localStorage behaviour.
  const notifications = useMemo(
    () => collection.items.slice(0, 40),
    [collection.items],
  );

  const push = useCallback(
    (input: NotificationPushInput) => {
      void collection.create({
        title: input.title,
        body: input.body,
        type: input.type ?? 'system',
        link: input.link ?? null,
        read: false,
      } as Partial<NotificationRow>);
    },
    [collection],
  );

  const markRead = useCallback(
    (id: string) => {
      void collection.update(id, { read: true } as Partial<NotificationRow>);
    },
    [collection],
  );

  const markAllRead = useCallback(() => {
    for (const item of notifications) {
      if (!item.read) void collection.update(item.id, { read: true } as Partial<NotificationRow>);
    }
  }, [collection, notifications]);

  const clearAll = useCallback(() => {
    for (const item of notifications) {
      void collection.remove(item.id);
    }
  }, [collection, notifications]);

  const unreadCount = useMemo(
    () => notifications.filter((n) => !n.read).length,
    [notifications],
  );

  const value = useMemo(
    () => ({ notifications, unreadCount, push, markRead, markAllRead, clearAll }),
    [notifications, unreadCount, push, markRead, markAllRead, clearAll],
  );

  return (
    <NotificationsContext.Provider value={value}>
      {children}
    </NotificationsContext.Provider>
  );
}

export function useNotifications(): NotificationsContextValue {
  const ctx = useContext(NotificationsContext);
  if (!ctx) {
    throw new Error('useNotifications must be used inside <NotificationsProvider>');
  }
  return ctx;
}