import {
  Activity,
  Apple,
  Brain,
  CalendarDays,
  ClipboardList,
  Droplet,
  FileClock,
  FileText,
  Flower2,
  Footprints,
  GlassWater,
  Heart,
  HeartPulse,
  LayoutDashboard,
  MessageSquare,
  Monitor,
  Moon,
  NotebookPen,
  Pill,
  ScanLine,
  Scale,
  ShieldCheck,
  Siren,
  Stethoscope,
  Users,
  Wind,
  Bot,
  FolderOpen,
  GraduationCap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const registry: Record<string, LucideIcon> = {
  heart: Heart,
  activity: Activity,
  droplet: Droplet,
  scale: Scale,
  moon: Moon,
  glass: GlassWater,
  apple: Apple,
  footprints: Footprints,
  pill: Pill,
  'shield-check': ShieldCheck,
  wind: Wind,
  brain: Brain,
  monitor: Monitor,
  flower: Flower2,
  messages: MessageSquare,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  users: Users,
  bot: Bot,
  scan: ScanLine,
  dashboard: LayoutDashboard,
  calendar: CalendarDays,
  journal: NotebookPen,
  'file-clock': FileClock,
  siren: Siren,
  clipboard: ClipboardList,
  folder: FolderOpen,
  graduation: GraduationCap,
  file: FileText,
};

export function iconFor(key: string, fallback: LucideIcon = Heart): LucideIcon {
  return registry[key] ?? fallback;
}
